from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import click
from rich.console import Console

console = Console()


@click.group("claims")
def claims_group() -> None:
    """Work with contested claims extracted from adversarial check findings."""


@claims_group.command("suggest")
@click.option("--branch", default=None,
              help="Branch to read findings from. Defaults to current git branch.")
@click.option("--dry-run", is_flag=True,
              help="Print stubs to stdout instead of writing wiki/claims.kt.")
@click.pass_context
def claims_suggest(ctx: click.Context, branch: str | None, dry_run: bool) -> None:
    """Generate @Contested TheoryOf stubs from contradiction check findings."""
    import subprocess
    from datetime import date
    from compost.checks.runner import branch_slug
    from compost.repo import find_repo_root

    repo = ctx.obj.get("repo") or find_repo_root(Path.cwd())
    if repo is None:
        console.print("[red]No .compost.yml found. Run from inside a compost wiki repo.[/red]")
        sys.exit(1)

    if branch is None:
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            cwd=repo, capture_output=True, text=True,
        )
        branch = result.stdout.strip() if result.returncode == 0 else "main"

    slug = branch_slug(branch)
    findings_path = repo / ".compost" / "checks" / f"{slug}.jsonl"

    if not findings_path.exists():
        console.print(f"[dim]No findings file found for branch '{branch}' ({findings_path.name}).[/dim]")
        console.print("[dim]Run 'compost checks run' on the branch first.[/dim]")
        return

    findings = _read_contradiction_findings(findings_path)

    if not findings:
        console.print(f"[dim]0 contradiction findings for branch '{branch}'.[/dim]")
        return

    date_str = date.today().isoformat()
    stubs = [_render_kotlin_stub(f, date_str, index=i) for i, f in enumerate(findings)]
    combined = "\n\n".join(stubs)

    if dry_run:
        console.print(combined)
        return

    claims_kt = repo / "wiki" / "claims.kt"
    if not claims_kt.exists():
        claims_kt.write_text(
            "// claims.kt — Contested theories extracted from compost check findings.\n"
            "// Each entry was generated by `compost claims suggest` and requires human review.\n"
            "// Edit freely: add context, promote to Disputes, or delete if resolved.\n\n"
        )

    existing = claims_kt.read_text()
    claims_kt.write_text(existing + combined + "\n")
    console.print(f"[green]{len(findings)} stub(s) written to wiki/claims.kt[/green]")


def _read_contradiction_findings(findings_path: Path) -> list[dict]:
    """Read JSONL sidecar; return only contradiction_scan findings with claim_text set."""
    if not findings_path.exists():
        return []
    results = []
    for line in findings_path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            record = json.loads(line)
        except json.JSONDecodeError:
            continue
        if (
            record.get("check") == "contradiction_scan"
            and record.get("claim_text")
        ):
            results.append(record)
    return results


def _render_kotlin_stub(finding: dict, date_str: str, *, index: int) -> str:
    """Render a single @Contested TheoryOf Kotlin stub from a contradiction finding."""
    page = finding.get("page", "unknown")
    var_name = "theory_" + re.sub(r"[^a-zA-Z0-9]", "_", page) + f"_{index}"
    claim = finding.get("claim_text", "")
    conflicting_page = finding.get("conflicting_page") or ""
    conflicting_claim = finding.get("conflicting_claim_text") or ""

    lines = [
        f"// Suggested by `compost claims suggest` on {date_str} — review before committing",
        "@Contested",
        f"val {var_name}: TheoryOf = TheoryOf(",
        f'    subject = TODO("resolve page: {page}"),',
        f'    claim = "{_escape_kt(claim)}",',
        f'    prov = Provenance(origin = "compost-checks", ingestedAt = "{date_str}", ingestedBy = "compost"),',
        ")",
    ]
    if conflicting_page:
        lines.append(f"// Conflicts with: {conflicting_page}")
    if conflicting_claim:
        lines.append(f'// Conflicting claim: "{_escape_kt(conflicting_claim)}"')

    return "\n".join(lines)


def _escape_kt(s: str) -> str:
    """Escape backslashes and double quotes for Kotlin string literals."""
    return s.replace("\\", "\\\\").replace('"', '\\"')
