from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

from compost.model.frontmatter import parse_frontmatter

# Matches: @Contested val NAME = TheoryOf(subject = PAGE_VAR, ...)
_CONTESTED_RE = re.compile(
    r"@Contested\s+val\s+(\w+)\s*=\s*TheoryOf\s*\(\s*subject\s*=\s*(\w+)",
    re.MULTILINE,
)
# Matches all TheoryOf declarations regardless of @Contested
_ALL_THEORY_RE = re.compile(
    r"val\s+(\w+)\s*=\s*TheoryOf\s*\(\s*subject\s*=\s*(\w+)",
    re.MULTILINE,
)


@dataclass
class ClaimsScan:
    all_theory_vars: list[str]
    contested_by_subject: dict[str, list[str]]


def _scan_claims(claims_kt: Path) -> ClaimsScan:
    """Regex-scan claims.kt for TheoryOf declarations.

    Relies on the keyword-argument convention: TheoryOf(subject = VAR_NAME, ...)
    """
    text = claims_kt.read_text()

    contested_by_subject: dict[str, list[str]] = defaultdict(list)
    for var_name, subject_var in _CONTESTED_RE.findall(text):
        contested_by_subject[subject_var].append(var_name)

    all_theory_vars = [var for var, _ in _ALL_THEORY_RE.findall(text)]

    return ClaimsScan(
        all_theory_vars=all_theory_vars,
        contested_by_subject=dict(contested_by_subject),
    )


_TYPE_MAP: dict[str, str] = {
    "service": "ServicePage",
    "module": "ServicePage",
    "decision": "DecisionPage",
    "runbook": "RunbookPage",
    "concept": "ConceptPage",
    "customer": "ConceptPage",
    "person": "PersonPage",
    "project": "ConceptPage",
    "incident": "IncidentPage",
    "research": "ConceptPage",
}

_SKIP_NAMES = {"glossary.md", "index.md", "log.md"}


@dataclass
class CodegenResult:
    kt_path: Path
    page_count: int
    dispute_count: int
    warnings: list[str]


def codify(repo: Path, *, wiki_dir: Path | None = None) -> CodegenResult:
    """Read all wiki/*.md, emit .compost/codify/generated/wiki.kt.

    Does not compile. Does not require kotlinc."""
    wiki_dir = wiki_dir or (repo / "wiki")
    out_dir = repo / ".compost" / "codify" / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)

    pages: list[tuple[Path, dict]] = []
    warnings: list[str] = []

    for md in sorted(wiki_dir.rglob("*.md")):
        if md.name in _SKIP_NAMES:
            continue
        fm, _ = parse_frontmatter(md)
        if not fm:
            warnings.append(f"{md.relative_to(repo)}: no frontmatter, skipped")
            continue
        pages.append((md, fm))

    # Scan claims.kt for @Contested TheoryOf to determine which pages are contested
    claims_kt = wiki_dir / "claims.kt"
    scan = _scan_claims(claims_kt) if claims_kt.exists() else ClaimsScan([], {})
    # Pages with 2+ @Contested TheoryOf become contested
    contested_var_names = {
        subject_var
        for subject_var, theory_vars in scan.contested_by_subject.items()
        if len(theory_vars) >= 2
    }

    name_dispute_count = _detect_disputes(pages)
    auto_dispute_count = len(contested_var_names)
    var_names: list[str] = []
    lines: list[str] = ["// Generated by compost codify — do not edit", ""]

    for md, fm in pages:
        rel = md.relative_to(repo)
        page_type = fm.get("type", "")
        kt_class = _TYPE_MAP.get(page_type)
        if kt_class is None:
            warnings.append(f"{rel}: unknown type '{page_type}', emitting UnknownPage")
            kt_class = "UnknownPage"

        var_name = _to_kotlin_ident(md.stem)
        var_names.append(var_name)
        prov = _emit_prov(rel, fm)
        contested = var_name in contested_var_names

        if kt_class == "ServicePage":
            lines.extend(_emit_service(var_name, md.stem, fm, prov, contested))
        elif kt_class == "DecisionPage":
            lines.extend(_emit_decision(var_name, md.stem, fm, prov, contested))
        elif kt_class == "RunbookPage":
            lines.extend(_emit_runbook(var_name, md.stem, fm, prov, contested))
        elif kt_class == "PersonPage":
            lines.extend(_emit_person(var_name, md.stem, fm, prov, contested))
        elif kt_class == "IncidentPage":
            lines.extend(_emit_incident(var_name, md.stem, fm, prov, contested))
        elif kt_class == "ConceptPage":
            lines.extend(_emit_concept(var_name, md.stem, fm, prov, contested))
        else:
            lines.extend(_emit_unknown(var_name, md.stem, fm, prov, page_type, contested))
        lines.append("")

    if var_names:
        lines.append(f"val allWikiPages: List<WikiPage> = listOf({', '.join(var_names)})")
    else:
        lines.append("val allWikiPages: List<WikiPage> = emptyList()")
    lines.append("")

    # Auto-generate Disputes for every subject that has 2+ @Contested TheoryOf
    today = str(date.today())
    auto_dispute_vars: list[str] = []
    for subject_var, theory_vars in scan.contested_by_subject.items():
        if len(theory_vars) >= 2:
            for i in range(len(theory_vars) - 1):
                dvar = f"{subject_var}_autoDispute_{i}"
                auto_dispute_vars.append(dvar)
                lines += [
                    f"// auto-generated: competing @Contested TheoryOf for {subject_var}",
                    f"val {dvar} = Disputes(",
                    f"    claimA = {theory_vars[i]},",
                    f"    claimB = {theory_vars[i + 1]},",
                    f'    prov = Provenance(origin = "compost-codify", ingestedAt = "{today}", ingestedBy = "compost-codify")',
                    ")",
                    "",
                ]

    # Collect all claims into allClaims for render_main.kt
    all_claim_vars = scan.all_theory_vars + auto_dispute_vars
    if all_claim_vars:
        lines.append(f"val allClaims: List<Any> = listOf({', '.join(all_claim_vars)})")
    else:
        lines.append("val allClaims: List<Any> = emptyList()")

    kt_path = out_dir / "wiki.kt"
    kt_path.write_text("\n".join(lines) + "\n")

    return CodegenResult(
        kt_path=kt_path,
        page_count=len(pages),
        dispute_count=name_dispute_count + auto_dispute_count,
        warnings=warnings,
    )


def _emit_prov(rel: Path, fm: dict) -> str:
    owners = fm.get("owners") or ["unknown"]
    ingested_by = owners[0] if isinstance(owners, list) else str(owners)
    updated = fm.get("updated") or ""
    sources = fm.get("sources") or []
    origin = sources[0] if sources else str(rel)
    return (
        f'Provenance(origin = {_qs(str(origin))}, '
        f'ingestedAt = {_qs(str(updated))}, '
        f'ingestedBy = {_qs(ingested_by)})'
    )


def _emit_service(var: str, stem: str, fm: dict, prov: str, contested: bool = False) -> list[str]:
    deps = _coerce_list(fm.get("depends_on"))
    tech = _coerce_list(fm.get("technology"))
    owner = _first_owner(fm)
    tier = int(fm.get("tier") or 2)
    return [
        f"val {var} = ServicePage(",
        f'    id = {_qs(stem)},',
        f'    title = {_qs(fm.get("name") or stem)},',
        f"    confidence = {_confidence_float(fm.get('confidence'))},",
        f"    prov = {prov},",
        f"    contested = {'true' if contested else 'false'},",
        f"    owner = {_qs(owner)},",
        f"    tier = {tier},",
        f"    dependsOn = {_kt_list(deps)},",
        f"    technology = {_kt_list(tech)},",
        ")",
    ]


def _emit_decision(var: str, stem: str, fm: dict, prov: str, contested: bool = False) -> list[str]:
    sups = _coerce_list(fm.get("supersedes"))
    return [
        f"val {var} = DecisionPage(",
        f'    id = {_qs(stem)},',
        f'    title = {_qs(fm.get("name") or stem)},',
        f"    confidence = {_confidence_float(fm.get('confidence'))},",
        f"    prov = {prov},",
        f"    contested = {'true' if contested else 'false'},",
        f'    status = {_qs(fm.get("status") or "proposed")},',
        f"    supersedes = {_kt_list(sups)},",
        ")",
    ]


def _emit_runbook(var: str, stem: str, fm: dict, prov: str, contested: bool = False) -> list[str]:
    return [
        f"val {var} = RunbookPage(",
        f'    id = {_qs(stem)},',
        f'    title = {_qs(fm.get("name") or stem)},',
        f"    confidence = {_confidence_float(fm.get('confidence'))},",
        f"    prov = {prov},",
        f"    contested = {'true' if contested else 'false'},",
        f"    owner = {_qs(_first_owner(fm))},",
        ")",
    ]


def _emit_concept(var: str, stem: str, fm: dict, prov: str, contested: bool = False) -> list[str]:
    return [
        f"val {var} = ConceptPage(",
        f'    id = {_qs(stem)},',
        f'    title = {_qs(fm.get("name") or stem)},',
        f"    confidence = {_confidence_float(fm.get('confidence'))},",
        f"    prov = {prov},",
        f"    contested = {'true' if contested else 'false'},",
        ")",
    ]


def _emit_person(var: str, stem: str, fm: dict, prov: str, contested: bool = False) -> list[str]:
    team = fm.get("team") or ""
    return [
        f"val {var} = PersonPage(",
        f'    id = {_qs(stem)},',
        f'    title = {_qs(fm.get("name") or stem)},',
        f"    confidence = {_confidence_float(fm.get('confidence'))},",
        f"    prov = {prov},",
        f"    contested = {'true' if contested else 'false'},",
        f"    team = {_qs(team)},",
        ")",
    ]


def _emit_incident(var: str, stem: str, fm: dict, prov: str, contested: bool = False) -> list[str]:
    severity = fm.get("severity") or ""
    return [
        f"val {var} = IncidentPage(",
        f'    id = {_qs(stem)},',
        f'    title = {_qs(fm.get("name") or stem)},',
        f"    confidence = {_confidence_float(fm.get('confidence'))},",
        f"    prov = {prov},",
        f"    contested = {'true' if contested else 'false'},",
        f'    status = {_qs(fm.get("status") or "open")},',
        f"    severity = {_qs(severity)},",
        ")",
    ]


def _emit_unknown(var: str, stem: str, fm: dict, prov: str, raw_type: str, contested: bool = False) -> list[str]:
    return [
        f"val {var} = UnknownPage(",
        f'    id = {_qs(stem)},',
        f'    title = {_qs(fm.get("name") or stem)},',
        f"    confidence = {_confidence_float(fm.get('confidence'))},",
        f"    prov = {prov},",
        f"    contested = {'true' if contested else 'false'},",
        f"    rawType = {_qs(raw_type)},",
        ")",
    ]


def _detect_disputes(pages: list[tuple[Path, dict]]) -> int:
    by_name: dict[str, list[Path]] = defaultdict(list)
    for md, fm in pages:
        name = (fm.get("name") or md.stem).lower()
        by_name[name].append(md)
        for alias in _coerce_list(fm.get("aliases")):
            by_name[alias.lower()].append(md)
    return sum(1 for v in by_name.values() if len(v) > 1)


def _to_kotlin_ident(stem: str) -> str:
    """hyphen/dot to camelCase; digit-leading stems get a 'p' prefix."""
    parts = stem.replace("-", "_").replace(".", "_").split("_")
    first = parts[0]
    rest = "".join(p.capitalize() for p in parts[1:])
    ident = first + rest
    if ident and ident[0].isdigit():
        ident = "p" + ident
    return ident


def _confidence_float(v) -> str:
    mapping = {"high": "0.9f", "medium": "0.7f", "low": "0.5f"}
    if isinstance(v, str):
        return mapping.get(v.lower(), "0.7f")
    if isinstance(v, (int, float)):
        return f"{float(v):.1f}f"
    return "0.7f"


def _esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _qs(s: str) -> str:
    return f'"{_esc(s)}"'


def _kt_list(items: list[str]) -> str:
    if not items:
        return "emptyList()"
    inner = ", ".join(_qs(i) for i in items)
    return f"listOf({inner})"


def _coerce_list(v) -> list[str]:
    if v is None:
        return []
    if isinstance(v, list):
        return [str(x) for x in v]
    return [str(v)]


def _first_owner(fm: dict) -> str:
    owners = fm.get("owners") or ["unknown"]
    if isinstance(owners, list):
        return owners[0] if owners else "unknown"
    return str(owners)
